apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: ghcr.io/cristovaoolegario/tasks-api:1.0.0
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DB_USER
              value: root
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: task-api-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: task-api-secret
                  key: PORT
            - name: BROKER_HOST
              value: "broker:29092"
            - name: MANAGER_NOTIFICATION_TOPIC
              valueFrom:
                secretKeyRef:
                  name: task-api-secret
                  key: MANAGER_NOTIFICATION_TOPIC
            - name: HEALTH_CHECK_PORT
              valueFrom:
                secretKeyRef:
                  name: task-api-secret
                  key: HEALTH_CHECK_PORT
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  type: LoadBalancer
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
