# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Setup repositories and dependencies for confluent-kafka-go
      # Two checkouts are needed - the argumentless version which checks out
      # confluent-kafka-go, and the other, which checks out librdkafka.
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: confluentinc/librdkafka
          path: './librdkafka'
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.3'
      - run: |
          sudo apt update
          sudo apt install -y libcurl4-openssl-dev libssl-dev libsasl2-dev libzstd-dev
      - run: |
          cd librdkafka
          ./configure --install-deps --enable-devel --disable-lz4-ext --prefix=/usr
          make
          sudo make install
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

